import {useEffect,useId,useRef,useState} from 'react';
import type {CanvasGraph,CanvasTest,CanvasDiagnostic,CanvasResult,CatalogEntry} from '../server/canvas.js';

export const emptyCanvas=():CanvasGraph=>({screens:[],edges:[],paths:[]});
const identity=()=>crypto.randomUUID();
export function CanvasBoard({graph,pathId,result,onMove,onSelect,selected}: {graph:CanvasGraph;pathId?:string;result?:CanvasResult;onMove?:(id:string,x:number,y:number)=>void;onSelect?:(id:string)=>void;selected?:string}){
 const [zoom,setZoom]=useState(.85);
 const surface=useRef<HTMLDivElement>(null);const [nodeHeights,setNodeHeights]=useState<Record<string,number>>({});
 useEffect(()=>{
  const observer=new ResizeObserver(entries=>{setNodeHeights(previous=>{const next={...previous};let changed=false;for(const entry of entries){const id=(entry.target as HTMLElement).dataset.screenId!;const height=entry.borderBoxSize[0]?.blockSize??entry.contentRect.height+2;if(next[id]!==height){next[id]=height;changed=true;}}return changed?next:previous;});});
  surface.current?.querySelectorAll('[data-screen-id]').forEach(element=>observer.observe(element));
  return()=>observer.disconnect();
 },[graph.screens]);
 const boardHeight=Math.max(1650,...graph.screens.map(screen=>screen.y+(nodeHeights[screen.id]??200)+120));const marker=useId().replaceAll(':','');
 const drag=useRef<{id:string;x:number;y:number;clientX:number;clientY:number}|undefined>(undefined);
 const route=graph.paths.find(path=>path.id===pathId);const selectedEdges=new Set(route?.edgeIds??[]);
 const selectedScreens=new Set(graph.edges.filter(edge=>selectedEdges.has(edge.id)).flatMap(edge=>[edge.from,edge.to]));
 function color(status?:string){return status==='passed'?'#c7ed88':status==='failed'?'#ef9b88':status==='skipped'?'#d8bc75':'#a7c8ed';}
 return <div className="canvas-board-wrap"><div className="canvas-toolbar"><span>Drag screen headers · arrows move a selected screen · scroll to pan</span><button onClick={()=>setZoom(value=>Math.max(.4,value-.1))} aria-label="Zoom out">−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(value=>Math.min(1.4,value+.1))} aria-label="Zoom in">+</button><button onClick={()=>setZoom(.85)}>Reset zoom</button></div>
 <div className="canvas-viewport" role="region" aria-label={result?'Executed screen canvas':'Screen test canvas'}><div style={{width:2700*zoom,height:boardHeight*zoom}}><div className="canvas-surface" ref={surface} style={{height:boardHeight,transform:`scale(${zoom})`}}>
 <svg className="canvas-lines" width="2700" height={boardHeight} aria-label="Screen transitions"><defs><marker id={marker} markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="context-stroke"/></marker></defs>{graph.edges.map(edge=>{
 const from=graph.screens.find(screen=>screen.id===edge.from);const to=graph.screens.find(screen=>screen.id===edge.to);if(!from||!to)return null;
 const start=[from.x+250,from.y+58];const end=[to.x,to.y+58];const middle=(start[0]+end[0])/2;const status=result?.edges.find(item=>item.id===edge.id)?.status;
 return <g key={edge.id} className={selectedEdges.has(edge.id)?'selected-transition':''}><path d={`M${start[0]},${start[1]} C${middle},${start[1]} ${middle},${end[1]} ${end[0]},${end[1]}`} stroke={selectedEdges.has(edge.id)?color(status):'#506257'} strokeWidth={selectedEdges.has(edge.id)?3:1.5} fill="none" markerEnd={`url(#${marker})`} strokeDasharray={selectedEdges.has(edge.id)?undefined:'6 5'}/><foreignObject x={middle-80} y={(start[1]+end[1])/2-36} width="160" height="48"><div className="transition-label">{edge.responseCondition}{selectedEdges.has(edge.id)&&<small>{status??'selected route'}</small>}</div></foreignObject></g>;
 })}</svg>
 {graph.screens.map(screen=>{const outcome=result?.screens.find(item=>item.id===screen.id)?.status;return <article key={screen.id} data-screen-id={screen.id} className={'screen-node '+(selectedScreens.has(screen.id)?'on-route ':'')+(selected===screen.id?'selected-screen':'')} style={{left:screen.x,top:screen.y,borderColor:selectedScreens.has(screen.id)?color(outcome):undefined}} aria-label={'Screen '+screen.title}>
 <button className="screen-node-heading" aria-label={'Select screen '+screen.title} onClick={()=>onSelect?.(screen.id)} onPointerDown={event=>{if(!onMove)return;event.currentTarget.setPointerCapture(event.pointerId);drag.current={id:screen.id,x:screen.x,y:screen.y,clientX:event.clientX,clientY:event.clientY};}} onPointerMove={event=>{const current=drag.current;if(!current||current.id!==screen.id)return;onMove?.(screen.id,Math.max(0,Math.min(2400,current.x+(event.clientX-current.clientX)/zoom)),Math.max(0,Math.min(1400,current.y+(event.clientY-current.clientY)/zoom)));}} onPointerUp={()=>{drag.current=undefined;}} onPointerCancel={()=>{drag.current=undefined;}} onKeyDown={event=>{const vectors:Record<string,[number,number]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};const direction=vectors[event.key];if(!direction||!onMove)return;event.preventDefault();const amount=event.shiftKey?40:10;onMove(screen.id,Math.max(0,Math.min(2400,screen.x+direction[0]*amount)),Math.max(0,Math.min(1400,screen.y+direction[1]*amount)));}}><span className="screen-icon">▣</span><span>{screen.title}<small>{screen.tests.length} associated tests / subflows</small></span><span className="node-handle"/></button>
 {screen.referenceScreenshot&&<img className="screen-reference" src={screen.referenceScreenshot} alt={'Reference for '+screen.title}/>}
 <div className="screen-test-list">{screen.tests.map(test=><div key={test.id} className="screen-test"><span>{test.label}<small>{test.role} · {test.reference.kind==='flow'?test.reference.file:`step ${(test.reference.index??0)+1}`}</small></span><span className={'outcome '+(result?.tests.find(item=>item.id===test.id)?.status??'unavailable')}>{result?.tests.find(item=>item.id===test.id)?.status??'linked'}</span></div>)}{!screen.tests.length&&<p>Associate YAML tests in the inspector.</p>}</div>
 </article>;})}
 {!graph.screens.length&&<div className="canvas-empty"><h3>Build your screen map</h3><p>Add a screen, associate its authored YAML tests, then connect expected transitions.</p></div>}
 </div></div></div></div>;
}

export function CanvasEditor({graph,onChange,catalog,diagnostics,pathId,onPathChange,disabled}:{graph:CanvasGraph|undefined;onChange:(graph:CanvasGraph|undefined)=>void;catalog:CatalogEntry[];diagnostics:CanvasDiagnostic[];pathId:string;onPathChange:(id:string)=>void;disabled:boolean}){
 const [selected,setSelected]=useState('');const [screenTitle,setScreenTitle]=useState('');
 const [referenceIndex,setReferenceIndex]=useState('');const [testLabel,setTestLabel]=useState('');const [role,setRole]=useState<CanvasTest['role']>('test');
 const [repairTest,setRepairTest]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [action,setAction]=useState('');const [assertion,setAssertion]=useState('');const [condition,setCondition]=useState('');const [pathName,setPathName]=useState('');const [nextEdge,setNextEdge]=useState('');const [error,setError]=useState('');
 const screen=graph?.screens.find(screen=>screen.id===selected);const path=graph?.paths.find(path=>path.id===pathId);
 const entry=catalog[Number(referenceIndex)];
 const apiId=useId();
 const currentGraph=useRef(graph);currentGraph.current=graph;
 const referenceVersion=catalog.map(entry=>entry.fingerprint).join(',');
 useEffect(()=>{setReferenceIndex('');},[referenceVersion]);
 function perform(update:()=>void){try{update();setError('');}catch(error){setError(error instanceof Error?error.message:'Canvas change failed.');}}
 function associate(){if(!graph||!screen||referenceIndex===''||!entry)throw new Error('Choose a screen and a current YAML reference.');const test={id:repairTest||identity(),label:testLabel.trim()||entry.label,role,reference:{kind:entry.kind,file:entry.file,index:entry.index,fingerprint:entry.fingerprint}};onChange({...graph,screens:graph.screens.map(item=>item.id===screen.id?{...item,tests:repairTest?item.tests.map(existing=>existing.id===repairTest?test:existing):[...item.tests,test]}:item)});setRepairTest('');setTestLabel('');}
 async function image(file?:File){if(!graph||!screen||!file)return;try{if(!['image/png','image/jpeg'].includes(file.type)||file.size>250_000)throw new Error('Use a PNG/JPEG reference up to 250 KB.');const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Reference image could not be read.'));reader.readAsDataURL(file);});const latest=currentGraph.current;if(!latest||!latest.screens.some(item=>item.id===screen.id))return;onChange({...latest,screens:latest.screens.map(item=>item.id===screen.id?{...item,referenceScreenshot:data}:item)});setError('');}catch(error){setError((error as Error).message);}}
 return <section className="canvas-editor" aria-labelledby="canvas-heading"><div className="label-row"><div><h2 id="canvas-heading">Screen test canvas</h2><p className="field-hint">One screen per node. YAML owns execution; select a route to review and map its results.</p></div><button className="confirm" disabled={disabled} onClick={()=>{onChange(graph?undefined:emptyCanvas());onPathChange('');}}>{graph?'Disable canvas':'Create screen canvas'}</button></div>
 {graph&&<>
 <div className="canvas-route-bar"><label htmlFor={apiId+'-path'}>Scenario path</label><select id={apiId+'-path'} value={pathId} disabled={disabled} onChange={event=>onPathChange(event.target.value)}><option value="">Explicitly select a route</option>{graph.paths.map(path=><option key={path.id} value={path.id}>{path.name}</option>)}</select><span>{path?.edgeIds.length??0} selected transitions</span></div>
 <CanvasBoard graph={graph} pathId={pathId} selected={selected} onSelect={id=>{setSelected(id);setRepairTest('');}} onMove={disabled?undefined:(id,x,y)=>onChange({...graph,screens:graph.screens.map(screen=>screen.id===id?{...screen,x,y}:screen)})}/>
 <p className="field-hint">Selecting a route does not rewrite YAML or enumerate graph paths. Run scenario executes the authored YAML only after its selected action/assertion order and references validate. Results map after the run; live per-step and #6 handler reporting are unavailable.</p>
 <div className="canvas-inspectors"><fieldset disabled={disabled}><legend>Screen inspector</legend><label htmlFor={apiId+'-new-screen'}>New screen title</label><input id={apiId+'-new-screen'} value={screenTitle} onChange={event=>setScreenTitle(event.target.value)} maxLength={120}/><button className="confirm" disabled={graph.screens.length>=40} onClick={()=>perform(()=>{if(!screenTitle.trim())throw new Error('Name the screen.');if(graph.screens.length>=40)throw new Error('This canvas supports up to 40 screens.');const id=identity();onChange({...graph,screens:[...graph.screens,{id,title:screenTitle.trim(),x:60+(graph.screens.length%7)*370,y:60+Math.floor(graph.screens.length/7)*260,tests:[]}]});setSelected(id);setScreenTitle('');})}>Add screen</button>
 <label htmlFor={apiId+'-screen'}>Selected screen</label><select id={apiId+'-screen'} value={selected} onChange={event=>{setSelected(event.target.value);setRepairTest('');}}><option value="">Choose a screen</option>{graph.screens.map(screen=><option key={screen.id} value={screen.id}>{screen.title}</option>)}</select>
 {screen&&<><label htmlFor={apiId+'-title'}>Screen title</label><input id={apiId+'-title'} value={screen.title} onChange={event=>onChange({...graph,screens:graph.screens.map(item=>item.id===screen.id?{...item,title:event.target.value}:item)})}/><label htmlFor={apiId+'-reference-image'}>Optional reference screenshot</label><input id={apiId+'-reference-image'} type="file" accept="image/png,image/jpeg" onChange={event=>void image(event.target.files?.[0])}/>{screen.referenceScreenshot&&<button className="text-button" onClick={()=>onChange({...graph,screens:graph.screens.map(item=>item.id===screen.id?{...item,referenceScreenshot:undefined}:item)})}>Remove reference image</button>}
 <label htmlFor={apiId+'-repair'}>Associated test to repair</label><select id={apiId+'-repair'} value={repairTest} onChange={event=>{setRepairTest(event.target.value);const test=screen.tests.find(test=>test.id===event.target.value);if(test){setTestLabel(test.label);setRole(test.role);}setReferenceIndex('');}}><option value="">Add a new association</option>{screen.tests.map(test=><option key={test.id} value={test.id}>{test.label}</option>)}</select>
 <label htmlFor={apiId+'-test-label'}>Test label</label><input id={apiId+'-test-label'} value={testLabel} onChange={event=>setTestLabel(event.target.value)} maxLength={120}/><label htmlFor={apiId+'-role'}>Test role</label><select id={apiId+'-role'} value={role} onChange={event=>setRole(event.target.value as CanvasTest['role'])}><option value="test">Test</option><option value="action">Triggering action</option><option value="assertion">Destination / shared assertion</option><option value="setup">Setup reference</option><option value="handler">Handler reference (#6 unavailable)</option></select>
 <label htmlFor={apiId+'-yaml-reference'}>Executable YAML reference</label><select id={apiId+'-yaml-reference'} value={referenceIndex} onChange={event=>setReferenceIndex(event.target.value)}><option value="">Choose an explicit command or reusable flow</option>{catalog.map((entry,index)=><option key={entry.kind+entry.file+(entry.index??'')} value={index}>{entry.label}{entry.assertion?' · assertion':''}</option>)}</select>{referenceIndex!==''&&entry&&<pre>{entry.preview}</pre>}<button className="confirm" onClick={()=>perform(associate)}>{repairTest?'Explicitly relink test':'Associate test'}</button>
 <details><summary>Discover this screen’s reusable tests</summary>{screen.tests.map(test=><div key={test.id}><strong>{test.label}</strong><p>{test.role} · {test.reference.file} {test.reference.kind==='step'?`step ${(test.reference.index??0)+1}`:''}</p>{diagnostics.filter(item=>item.ownerId===test.id).map((item,index)=><p className="reference-error" key={index}>{item.detail}</p>)}</div>)}</details>
 <button className="text-button" onClick={()=>onChange({...graph,screens:graph.screens.filter(item=>item.id!==screen.id)})}>Remove screen (references remain visible for repair)</button></>}
 </fieldset>
 <fieldset disabled={disabled}><legend>Connect expected screens</legend><label htmlFor={apiId+'-from'}>Source screen</label><select id={apiId+'-from'} value={from} onChange={event=>{setFrom(event.target.value);setAction('');}}><option value="">Choose source</option>{graph.screens.map(screen=><option key={screen.id} value={screen.id}>{screen.title}</option>)}</select><label htmlFor={apiId+'-action'}>Triggering YAML test</label><select id={apiId+'-action'} value={action} onChange={event=>setAction(event.target.value)}><option value="">Choose source test</option>{graph.screens.find(screen=>screen.id===from)?.tests.map(test=><option key={test.id} value={test.id}>{test.label}</option>)}</select>
 <label htmlFor={apiId+'-to'}>Expected destination</label><select id={apiId+'-to'} value={to} onChange={event=>{setTo(event.target.value);setAssertion('');}}><option value="">Choose destination</option>{graph.screens.map(screen=><option key={screen.id} value={screen.id}>{screen.title}</option>)}</select><label htmlFor={apiId+'-assert'}>Destination assertion / reusable flow</label><select id={apiId+'-assert'} value={assertion} onChange={event=>setAssertion(event.target.value)}><option value="">Choose destination test</option>{graph.screens.find(screen=>screen.id===to)?.tests.map(test=><option key={test.id} value={test.id}>{test.label}</option>)}</select>
 <label htmlFor={apiId+'-condition'}>Response condition / transition explanation</label><input id={apiId+'-condition'} value={condition} onChange={event=>setCondition(event.target.value)} placeholder="Example: HTTP 500 → maintenance" maxLength={300}/><button className="confirm" onClick={()=>perform(()=>{if(!from||!to||!action||!assertion||!condition.trim())throw new Error('Choose both screens, tests and response condition.');onChange({...graph,edges:[...graph.edges,{id:identity(),from,to,actionTestId:action,assertionTestId:assertion,responseCondition:condition.trim()}]});})}>Connect screens</button>
 <ul className="canvas-edge-list">{graph.edges.map(edge=><li key={edge.id}>{graph.screens.find(screen=>screen.id===edge.from)?.title??'Missing screen'} → {graph.screens.find(screen=>screen.id===edge.to)?.title??'Missing screen'}<small>{edge.responseCondition}</small><button className="text-button" onClick={()=>onChange({...graph,edges:graph.edges.filter(item=>item.id!==edge.id)})}>Remove transition</button></li>)}</ul>
 </fieldset>
 <fieldset disabled={disabled}><legend>Choose an explicit route</legend><label htmlFor={apiId+'-path-name'}>New scenario path name</label><input id={apiId+'-path-name'} value={pathName} onChange={event=>setPathName(event.target.value)} maxLength={120}/><button className="confirm" onClick={()=>perform(()=>{if(!pathName.trim())throw new Error('Name the scenario path.');const id=identity();onChange({...graph,paths:[...graph.paths,{id,name:pathName.trim(),edgeIds:[]}]});onPathChange(id);setPathName('');})}>Create path</button>
 {path&&<><label htmlFor={apiId+'-next-edge'}>Next transition in selected path</label><select id={apiId+'-next-edge'} value={nextEdge} onChange={event=>setNextEdge(event.target.value)}><option value="">Choose a transition</option>{graph.edges.map(edge=><option key={edge.id} value={edge.id}>{graph.screens.find(screen=>screen.id===edge.from)?.title??'?'} → {graph.screens.find(screen=>screen.id===edge.to)?.title??'?'} · {edge.responseCondition}</option>)}</select><button className="confirm" onClick={()=>perform(()=>{if(!nextEdge)throw new Error('Choose the next transition.');onChange({...graph,paths:graph.paths.map(item=>item.id===path.id?{...item,edgeIds:[...item.edgeIds,nextEdge]}:item)});setNextEdge('');})}>Append transition to path</button><ol>{path.edgeIds.map((id,index)=><li key={index}>{graph.edges.find(edge=>edge.id===id)?.responseCondition??'Missing transition'} <button className="text-button" onClick={()=>onChange({...graph,paths:graph.paths.map(item=>item.id===path.id?{...item,edgeIds:item.edgeIds.filter((_id,i)=>i!==index)}:item)})}>Remove from path</button></li>)}</ol></>}
 </fieldset></div>
 {diagnostics.length>0&&<div className="notice error" role="alert"><strong>References need review</strong>{diagnostics.map((diagnostic,index)=><p key={index}>{graph.screens.flatMap(screen=>screen.tests).find(test=>test.id===diagnostic.ownerId)?.label??diagnostic.ownerId}: {diagnostic.detail}</p>)}</div>}
 {error&&<div className="notice error" role="alert">{error}</div>}
 </>}
 </section>;
}
